### ISSUE TITLE
fix text borders for browser zoom 

### ISSUE THREAD

**Issue by themighty1** [tlsnotary/docs-mdbook#54]
Currently, when Firefox zoom level is set to 150%, this is what I see:
(same for Chrome)

![Screenshot from 2023-12-20 07-40-44](https://github.com/tlsnotary/docs-mdbook/assets/555272/e1b4f761-964b-49e7-a577-1a3116036535)

**Comment by heeckhau** [comment]
This should be fixed in #56

**Comment by themighty1** [comment]
thanks, works for me
