### ISSUE TITLE
Document websocket proxy

### ISSUE THREAD

**Issue by sinui0** [tlsnotary/docs-mdbook#81]
Recently there was confusion around the role/security implications of the websocket proxy we use for browser deployments. We should document it, particularly the fact that it does _not_ see any unencrypted application data.

**Comment by themighty1** [comment]
While this can be documented in the `Browser extension`, we can also extract some of the stumbling blocks into the FAQ section. I'll open a new issue where we could list some things that deseve to be put in an FAQ section.

**Comment by maceip** [comment]
#93
