### ISSUE TITLE
Confusion between Notary and Verifier

### ISSUE THREAD

**Issue by Flydexo** [tlsnotary/docs-mdbook#87]
Isn't the session Header signed by the notary

<img width="525" alt="Screenshot 2024-07-12 at 12 40 12" src="https://github.com/user-attachments/assets/87db7351-11b7-493c-b7be-1d595dd811ce">

Image from the Verification page in the [docs](https://docs.tlsnotary.org/protocol/verification.html)

**Comment by themighty1** [comment]
you are right, sorry for the confusion, will add a fix soon
